name: Infrastructure Validation
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Verify structure
        run: |
          echo "✓ Repository structure validated"
          ls -la
          
      - name: Check Terraform files
        run: |
          if [ -d "terraform" ]; then
            echo "✓ Terraform directory exists"
            ls -la terraform/
          else
            echo "⚠ Terraform directory not found (will be added later)"
          fi
      
      - name: Success
        run: echo "✓ Infrastructure validation passed"
